version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: semillabitcoin-frigate_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/4rkad/frigate-umbrel-web:1.5.2-5@sha256:26c8d8a26a8cc91564229f0b1ceb14e7dce8e3c139be57714b550aff388941de
    restart: on-failure
    depends_on:
      init:
        condition: service_completed_successfully
    volumes:
      - ${APP_DATA_DIR}/icon.png:/usr/share/nginx/html/icon.png:ro
      - ${APP_DATA_DIR}/data/frigate.log:/usr/share/nginx/html/frigate.log:ro
    environment:
      FRIGATE_TOR_ADDRESS: "${APP_FRIGATE_RPC_HIDDEN_SERVICE}"
      FRIGATE_VERSION: "${APP_VERSION}"
    command: ["sh", "-c", "envsubst '$$FRIGATE_TOR_ADDRESS $$FRIGATE_VERSION' < /tmp/index.template.html > /usr/share/nginx/html/index.html && exec nginx -g 'daemon off;'"]

  init:
    image: alpine:3.20
    user: "0:0"
    restart: "no"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command: ["sh", "-c", "mkdir -p /data && touch /data/frigate.log && chmod 644 /data/frigate.log && chown -R 1000:1000 /data && chmod 755 /data && chmod 644 /data/frigate.log"]

  server:
    image: ghcr.io/4rkad/frigate-umbrel:1.5.2-5@sha256:122338455a8ccb367b199e033ab135fbf3280913ddd66cae8357b7de8ac9f3bf
    user: "0:0"
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - "57001:57001"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_BITCOIN_DATA_DIR}:/data/.bitcoin:ro
    environment:
      APP_BITCOIN_NODE_IP: ${APP_BITCOIN_NODE_IP}
      APP_BITCOIN_RPC_PORT: ${APP_BITCOIN_RPC_PORT}
      APP_BITCOIN_ZMQ_SEQUENCE_PORT: ${APP_BITCOIN_ZMQ_SEQUENCE_PORT}
      FRIGATE_BITCOIN_DATA_DIR: "/data/.bitcoin"
      FRIGATE_BACKEND_ELECTRUM: "tcp://${APP_ELECTRS_NODE_IP}:${APP_ELECTRS_NODE_PORT}"
      FRIGATE_NETWORK: ${APP_BITCOIN_NETWORK:-mainnet}
      FRIGATE_COMPUTE_BACKEND: "CPU"
      FRIGATE_PORT: "57001"

  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: "/tmp"
    entrypoint: ["/bin/sh", "-c"]
    command: ["mkdir -p /data/app-semillabitcoin-frigate/main && chmod 700 /data/app-semillabitcoin-frigate/main && printf 'HiddenServiceDir /data/app-semillabitcoin-frigate/main\\nHiddenServicePort 57001 semillabitcoin-frigate_server_1:57001\\n' > /tmp/torrc && exec tor -f /tmp/torrc"]
