version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ${APP_SEMILLABITCOIN_BROADCAST_POOL_IP}
      APP_PORT: ${APP_SEMILLABITCOIN_BROADCAST_POOL_PORT}

  app:
    image: ghcr.io/semillabitcoin/broadcast-pool:v0.3.16@sha256:cd7f691557f9a19484b9577ef058e814faf55be764e29db232234feb6e4f0e63
    init: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "50005:50005"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      ELECTRUM_HOST: ${APP_ELECTRS_NODE_IP}
      ELECTRUM_PORT: ${APP_ELECTRS_NODE_PORT}
      DB_PATH: /data/pool.db
      WEB_PORT: "4040"
      WEB_BIND: "0.0.0.0"
      PROXY_PORT: "50005"
      APP_SEED: ${APP_SEED}
      APP_PASSWORD: ${APP_PASSWORD}
      APP_HIDDEN_SERVICE: ${APP_HIDDEN_SERVICE}
    networks:
      default:
        ipv4_address: ${APP_SEMILLABITCOIN_BROADCAST_POOL_IP}
