version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ${APP_SEMILLABITCOIN_BROADCAST_POOL_IP}
      APP_PORT: ${APP_SEMILLABITCOIN_BROADCAST_POOL_PORT}

  app:
    image: ghcr.io/semillabitcoin/broadcast-pool:v0.2.5@sha256:4fbe47d8a1ca755ebb026dfd3f9892ea91e982e5ad227483881b0c278efbd28f
    init: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "50005:50005"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      ELECTRUM_HOST: ${APP_ELECTRS_NODE_IP}
      ELECTRUM_PORT: ${APP_ELECTRS_NODE_PORT}
      DB_PATH: /data/pool.db
      WEB_PORT: "4040"
      WEB_BIND: "0.0.0.0"
      PROXY_PORT: "50005"
      APP_SEED: ${APP_SEED}
      APP_PASSWORD: ${APP_PASSWORD}
      APP_HIDDEN_SERVICE: ${APP_HIDDEN_SERVICE}
    networks:
      default:
        ipv4_address: ${APP_SEMILLABITCOIN_BROADCAST_POOL_IP}
